server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:2221/BKG?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false


