server:
  port: 4444

spring:
  datasource:
    url: jdbc:mysql://localhost:6666/DBL?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false


